### ISSUE TITLE
Dependency on Mojo::Base not declared

### ISSUE THREAD

**Issue by andk** [jhthorsen/mojolicious-plugin-loop#1]
Hi Marcus,

as per subject. Grep:

http://search.cpan.org/grep?release=Mojolicious-Plugin-Loop-0.02;string=Mojo::Base;n=1;C=0

This leads to fail reports, at the moment already 119, e.g.:

http://www.cpantesters.org/cpan/report/87252365

HTH && Thanks,

**Comment by jhthorsen** [comment]
Thank you @andk! I will soon make a new release to CPAN.

👍
